name: expense_tracker
description: A comprehensive expense tracking application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  fl_chart: ^0.64.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  flutter_local_notifications: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 