name: expense_tracker
description: A comprehensive expense tracking application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  fl_chart: ^0.65.0
  excel: ^4.0.2
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  google_fonts: ^6.1.0
  file_selector: ^1.0.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.3.2+1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true 